@port = 3000
@base_url = http://localhost:{{ port }}/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzIyODkwOTI4LCJleHAiOjE3MjI4OTQ1Mjh9.q5Hg24In5pENUh0l_5pNqzae3NC4Mt52JmF8alZRoKQ


### Register User
POST {{ base_url }}/auth/register
Content-Type: application/json

{
    "username": "hafna",
    "email": "hafna@gmail.com",
    "password": "hafna123"
}

### Login User
POST {{ base_url }}/auth/login
Content-Type: application/json

{
    "username": "haidar",
    "password": "haidar123"
}

### Refresh Token
POST {{ base_url }}/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "a654808d-1603-4881-a230-25cd534f92ff"
}

### Get User
GET {{ base_url }}/users
Authorization: Bearer {{token}}

### Get User By Id
GET {{ base_url }}/users/2
Authorization: Bearer {{token}}

### Update User
PUT {{ base_url }}/users/update/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "is_admin": false
}

### Delete User
DELETE {{ base_url }}/users/delete/3
Authorization: Bearer {{token}}


### Get All Laporans
GET {{ base_url }}/laporans
Authorization: Bearer {{token}}

### Get Laporan By Id
GET {{ base_url }}/laporans/2
Authorization: Bearer {{token}}

### Create Laporan
POST {{ base_url }}/laporans/create
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token}}

--boundary
Content-Disposition: form-data; name="title"

Laporan 2 png
--boundary
Content-Disposition: form-data; name="description"

Laporan 2 png Description
--boundary
Content-Disposition: form-data; name="status"

Penting
--boundary
Content-Disposition: form-data; name="photo"; filename="laporan.png"
Content-Type: image/jpeg

< C:\Users\hilmy\OneDrive\Pictures\9ed76d611947c5ac25dfe6449ee82712.jpg
--boundary--